import { useEffect, useId, useRef, useState, type KeyboardEvent } from 'react'
import {
  CalendarDays,
  Music,
  Mic2,
  Headphones,
  Radio,
  PartyPopper,
  Balloon,
  Cake,
  Gift,
  Crown,
  Heart,
  HandHeart,
  Star,
  Sparkles,
  Diamond,
  Gem,
  Smile,
  Laugh,
  Users,
  Handshake,
  Baby,
  Home,
  Plane,
  TrainFront,
  Car,
  Bus,
  Bike,
  Ship,
  Sailboat,
  Rocket,
  MapPin,
  Compass,
  Tent,
  Mountain,
  Palmtree,
  Trees,
  Leaf,
  Flower2,
  Sun,
  Moon,
  CloudSun,
  Snowflake,
  Umbrella,
  Flame,
  Droplets,
  Camera,
  Film,
  Clapperboard,
  Popcorn,
  Ticket,
  Drama,
  Tv,
  Gamepad2,
  Trophy,
  Medal,
  Dumbbell,
  Target,
  Flag,
  Coffee,
  Beer,
  Wine,
  Utensils,
  Pizza,
  Sandwich,
  Soup,
  IceCreamCone,
  Apple,
  Cherry,
  Egg,
  Fish,
  Dog,
  Cat,
  Bird,
  Rabbit,
  Turtle,
  Squirrel,
  PawPrint,
  Bone,
  Bug,
  Shell,
  BookOpen,
  School,
  GraduationCap,
  Briefcase,
  Building2,
  Store,
  Landmark,
  Church,
  Hospital,
  Warehouse,
  Phone,
  Smartphone,
  Laptop,
  Mail,
  MessageCircle,
  Bell,
  Lock,
  Key,
  Watch,
  AlarmClock,
  Timer,
  Hourglass,
  PenLine,
  Palette,
  Brush,
  Scissors,
  Wrench,
  Hammer,
  Anchor,
  Aperture,
  Archive,
  Armchair,
  Award,
  Axe,
  Backpack,
  Banana,
  Banknote,
  Bath,
  BedDouble,
  Binoculars,
  Bomb,
  BookMarked,
  Bookmark,
  Bot,
  Box,
  Brain,
  BrickWall,
  BusFront,
  Calculator,
  CalendarHeart,
  Candy,
  CandyCane,
  CarFront,
  Carrot,
  Castle,
  ChefHat,
  Citrus,
  Clipboard,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  Clover,
  Code,
  Cog,
  Coins,
  Cookie,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Crosshair,
  CupSoda,
  Dessert,
  Dice5,
  Dices,
  Disc3,
  Dna,
  Donut,
  DoorOpen,
  Drum,
  Ear,
  Earth,
  Eclipse,
  EggFried,
  Eye,
  Factory,
  Fan,
  Feather,
  FerrisWheel,
  FileMusic,
  Fingerprint,
  FireExtinguisher,
  FlaskConical,
  Footprints,
  Fuel,
  Ghost,
  GlassWater,
  Globe,
  Goal,
  Grape,
  Guitar,
  Hand,
  HardHat,
  HeartHandshake,
  HeartPulse,
  Hotel,
  IceCreamBowl,
  Joystick,
  Lamp,
  Languages,
  Library,
  LifeBuoy,
  Lightbulb,
  Lollipop,
  Luggage,
  Magnet,
  Map,
  Martini,
  Megaphone,
  MicVocal,
  Milk,
  Monitor,
  MoonStar,
  MountainSnow,
  Mouse,
  Music2,
  Music3,
  Music4,
  Newspaper,
  Notebook,
  Nut,
  Orbit,
  Package,
  Paintbrush,
  ParkingMeter,
  Piano,
  PiggyBank,
  Pill,
  PlaneTakeoff,
  Plug,
  PocketKnife,
  Podcast,
  Printer,
  Projector,
  Puzzle,
  QrCode,
  Rainbow,
  Rat,
  Receipt,
  Refrigerator,
  Ribbon,
  RollerCoaster,
  Rose,
  Route,
  Ruler,
  Salad,
  Satellite,
  ScanFace,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shrub,
  Skull,
  Snail,
  Sofa,
  Speaker,
  Sprout,
  Stethoscope,
  SunMoon,
  Sunrise,
  Sunset,
  Sword,
  Swords,
  Syringe,
  Tag,
  TentTree,
  Theater,
  ThumbsUp,
  ToyBrick,
  Tractor,
  TrafficCone,
  TreePine,
  Truck,
  User,
  VenetianMask,
  Video,
  Volume2,
  WandSparkles,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Worm,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import './EventNameField.css'

export type EventIconId = string

type EventIconOption = {
  id: EventIconId
  label: string
  Icon: LucideIcon
}

export const EVENT_ICON_OPTIONS: EventIconOption[] = [
  { id: 'calendar-days', label: '予定', Icon: CalendarDays },
  { id: 'music', label: '音楽', Icon: Music },
  { id: 'mic2', label: 'ライブ', Icon: Mic2 },
  { id: 'headphones', label: 'ヘッドホン', Icon: Headphones },
  { id: 'radio', label: 'ラジオ', Icon: Radio },
  { id: 'party-popper', label: 'パーティー', Icon: PartyPopper },
  { id: 'balloon', label: 'バルーン', Icon: Balloon },
  { id: 'cake', label: 'ケーキ', Icon: Cake },
  { id: 'gift', label: 'ギフト', Icon: Gift },
  { id: 'crown', label: 'クラウン', Icon: Crown },
  { id: 'heart', label: 'ハート', Icon: Heart },
  { id: 'hand-heart', label: 'Hand Heart', Icon: HandHeart },
  { id: 'star', label: 'スター', Icon: Star },
  { id: 'sparkles', label: 'きらきら', Icon: Sparkles },
  { id: 'diamond', label: 'Diamond', Icon: Diamond },
  { id: 'gem', label: 'Gem', Icon: Gem },
  { id: 'smile', label: 'スマイル', Icon: Smile },
  { id: 'laugh', label: 'Laugh', Icon: Laugh },
  { id: 'users', label: '友達', Icon: Users },
  { id: 'handshake', label: 'Handshake', Icon: Handshake },
  { id: 'baby', label: 'Baby', Icon: Baby },
  { id: 'home', label: '家', Icon: Home },
  { id: 'plane', label: '飛行機', Icon: Plane },
  { id: 'train-front', label: '電車', Icon: TrainFront },
  { id: 'car', label: '車', Icon: Car },
  { id: 'bus', label: 'Bus', Icon: Bus },
  { id: 'bike', label: 'Bike', Icon: Bike },
  { id: 'ship', label: 'Ship', Icon: Ship },
  { id: 'sailboat', label: 'Sailboat', Icon: Sailboat },
  { id: 'rocket', label: 'Rocket', Icon: Rocket },
  { id: 'map-pin', label: 'Map Pin', Icon: MapPin },
  { id: 'compass', label: 'Compass', Icon: Compass },
  { id: 'tent', label: 'Tent', Icon: Tent },
  { id: 'mountain', label: 'Mountain', Icon: Mountain },
  { id: 'palmtree', label: 'Palmtree', Icon: Palmtree },
  { id: 'trees', label: 'Trees', Icon: Trees },
  { id: 'leaf', label: 'Leaf', Icon: Leaf },
  { id: 'flower2', label: 'Flower 2', Icon: Flower2 },
  { id: 'sun', label: 'Sun', Icon: Sun },
  { id: 'moon', label: 'Moon', Icon: Moon },
  { id: 'cloud-sun', label: 'Cloud Sun', Icon: CloudSun },
  { id: 'snowflake', label: 'Snowflake', Icon: Snowflake },
  { id: 'umbrella', label: 'Umbrella', Icon: Umbrella },
  { id: 'flame', label: 'Flame', Icon: Flame },
  { id: 'droplets', label: 'Droplets', Icon: Droplets },
  { id: 'camera', label: 'カメラ', Icon: Camera },
  { id: 'film', label: 'Film', Icon: Film },
  { id: 'clapperboard', label: 'Clapperboard', Icon: Clapperboard },
  { id: 'popcorn', label: 'Popcorn', Icon: Popcorn },
  { id: 'ticket', label: 'Ticket', Icon: Ticket },
  { id: 'drama', label: 'Drama', Icon: Drama },
  { id: 'tv', label: 'Tv', Icon: Tv },
  { id: 'gamepad2', label: 'Gamepad 2', Icon: Gamepad2 },
  { id: 'trophy', label: 'Trophy', Icon: Trophy },
  { id: 'medal', label: 'Medal', Icon: Medal },
  { id: 'dumbbell', label: 'Dumbbell', Icon: Dumbbell },
  { id: 'target', label: 'Target', Icon: Target },
  { id: 'flag', label: 'Flag', Icon: Flag },
  { id: 'coffee', label: 'コーヒー', Icon: Coffee },
  { id: 'beer', label: 'Beer', Icon: Beer },
  { id: 'wine', label: 'Wine', Icon: Wine },
  { id: 'utensils', label: 'Utensils', Icon: Utensils },
  { id: 'pizza', label: 'ピザ', Icon: Pizza },
  { id: 'sandwich', label: 'Sandwich', Icon: Sandwich },
  { id: 'soup', label: 'Soup', Icon: Soup },
  { id: 'ice-cream-cone', label: 'Ice Cream Cone', Icon: IceCreamCone },
  { id: 'apple', label: 'Apple', Icon: Apple },
  { id: 'cherry', label: 'Cherry', Icon: Cherry },
  { id: 'egg', label: 'Egg', Icon: Egg },
  { id: 'fish', label: 'Fish', Icon: Fish },
  { id: 'dog', label: '犬', Icon: Dog },
  { id: 'cat', label: '猫', Icon: Cat },
  { id: 'bird', label: 'Bird', Icon: Bird },
  { id: 'rabbit', label: 'Rabbit', Icon: Rabbit },
  { id: 'turtle', label: 'Turtle', Icon: Turtle },
  { id: 'squirrel', label: 'Squirrel', Icon: Squirrel },
  { id: 'paw-print', label: 'Paw Print', Icon: PawPrint },
  { id: 'bone', label: 'Bone', Icon: Bone },
  { id: 'bug', label: 'Bug', Icon: Bug },
  { id: 'shell', label: 'Shell', Icon: Shell },
  { id: 'book-open', label: '本', Icon: BookOpen },
  { id: 'school', label: 'School', Icon: School },
  { id: 'graduation-cap', label: 'Graduation Cap', Icon: GraduationCap },
  { id: 'briefcase', label: 'Briefcase', Icon: Briefcase },
  { id: 'building2', label: 'Building 2', Icon: Building2 },
  { id: 'store', label: 'Store', Icon: Store },
  { id: 'landmark', label: 'Landmark', Icon: Landmark },
  { id: 'church', label: 'Church', Icon: Church },
  { id: 'hospital', label: 'Hospital', Icon: Hospital },
  { id: 'warehouse', label: 'Warehouse', Icon: Warehouse },
  { id: 'phone', label: 'Phone', Icon: Phone },
  { id: 'smartphone', label: 'Smartphone', Icon: Smartphone },
  { id: 'laptop', label: 'Laptop', Icon: Laptop },
  { id: 'mail', label: 'Mail', Icon: Mail },
  { id: 'message-circle', label: 'Message Circle', Icon: MessageCircle },
  { id: 'bell', label: 'Bell', Icon: Bell },
  { id: 'lock', label: 'Lock', Icon: Lock },
  { id: 'key', label: 'Key', Icon: Key },
  { id: 'watch', label: 'Watch', Icon: Watch },
  { id: 'alarm-clock', label: 'Alarm Clock', Icon: AlarmClock },
  { id: 'timer', label: 'Timer', Icon: Timer },
  { id: 'hourglass', label: 'Hourglass', Icon: Hourglass },
  { id: 'pen-line', label: 'Pen Line', Icon: PenLine },
  { id: 'palette', label: 'Palette', Icon: Palette },
  { id: 'brush', label: 'Brush', Icon: Brush },
  { id: 'scissors', label: 'Scissors', Icon: Scissors },
  { id: 'wrench', label: 'Wrench', Icon: Wrench },
  { id: 'hammer', label: 'Hammer', Icon: Hammer },
  { id: 'anchor', label: 'Anchor', Icon: Anchor },
  { id: 'aperture', label: 'Aperture', Icon: Aperture },
  { id: 'archive', label: 'Archive', Icon: Archive },
  { id: 'armchair', label: 'Armchair', Icon: Armchair },
  { id: 'award', label: 'Award', Icon: Award },
  { id: 'axe', label: 'Axe', Icon: Axe },
  { id: 'backpack', label: 'Backpack', Icon: Backpack },
  { id: 'banana', label: 'Banana', Icon: Banana },
  { id: 'banknote', label: 'Banknote', Icon: Banknote },
  { id: 'bath', label: 'Bath', Icon: Bath },
  { id: 'bed-double', label: 'Bed Double', Icon: BedDouble },
  { id: 'binoculars', label: 'Binoculars', Icon: Binoculars },
  { id: 'bomb', label: 'Bomb', Icon: Bomb },
  { id: 'book-marked', label: 'Book Marked', Icon: BookMarked },
  { id: 'bookmark', label: 'Bookmark', Icon: Bookmark },
  { id: 'bot', label: 'Bot', Icon: Bot },
  { id: 'box', label: 'Box', Icon: Box },
  { id: 'brain', label: 'Brain', Icon: Brain },
  { id: 'brick-wall', label: 'Brick Wall', Icon: BrickWall },
  { id: 'bus-front', label: 'Bus Front', Icon: BusFront },
  { id: 'calculator', label: 'Calculator', Icon: Calculator },
  { id: 'calendar-heart', label: 'Calendar Heart', Icon: CalendarHeart },
  { id: 'candy', label: 'Candy', Icon: Candy },
  { id: 'candy-cane', label: 'Candy Cane', Icon: CandyCane },
  { id: 'car-front', label: 'Car Front', Icon: CarFront },
  { id: 'carrot', label: 'Carrot', Icon: Carrot },
  { id: 'castle', label: 'Castle', Icon: Castle },
  { id: 'chef-hat', label: 'Chef Hat', Icon: ChefHat },
  { id: 'citrus', label: 'Citrus', Icon: Citrus },
  { id: 'clipboard', label: 'Clipboard', Icon: Clipboard },
  { id: 'clock', label: 'Clock', Icon: Clock },
  { id: 'cloud', label: 'Cloud', Icon: Cloud },
  { id: 'cloud-lightning', label: 'Cloud Lightning', Icon: CloudLightning },
  { id: 'cloud-rain', label: 'Cloud Rain', Icon: CloudRain },
  { id: 'clover', label: 'Clover', Icon: Clover },
  { id: 'code', label: 'Code', Icon: Code },
  { id: 'cog', label: 'Cog', Icon: Cog },
  { id: 'coins', label: 'Coins', Icon: Coins },
  { id: 'cookie', label: 'Cookie', Icon: Cookie },
  { id: 'cooking-pot', label: 'Cooking Pot', Icon: CookingPot },
  { id: 'cpu', label: 'Cpu', Icon: Cpu },
  { id: 'credit-card', label: 'Credit Card', Icon: CreditCard },
  { id: 'croissant', label: 'Croissant', Icon: Croissant },
  { id: 'crosshair', label: 'Crosshair', Icon: Crosshair },
  { id: 'cup-soda', label: 'Cup Soda', Icon: CupSoda },
  { id: 'dessert', label: 'Dessert', Icon: Dessert },
  { id: 'dice5', label: 'Dice 5', Icon: Dice5 },
  { id: 'dices', label: 'Dices', Icon: Dices },
  { id: 'disc3', label: 'Disc 3', Icon: Disc3 },
  { id: 'dna', label: 'Dna', Icon: Dna },
  { id: 'donut', label: 'Donut', Icon: Donut },
  { id: 'door-open', label: 'Door Open', Icon: DoorOpen },
  { id: 'drum', label: 'Drum', Icon: Drum },
  { id: 'ear', label: 'Ear', Icon: Ear },
  { id: 'earth', label: 'Earth', Icon: Earth },
  { id: 'eclipse', label: 'Eclipse', Icon: Eclipse },
  { id: 'egg-fried', label: 'Egg Fried', Icon: EggFried },
  { id: 'eye', label: 'Eye', Icon: Eye },
  { id: 'factory', label: 'Factory', Icon: Factory },
  { id: 'fan', label: 'Fan', Icon: Fan },
  { id: 'feather', label: 'Feather', Icon: Feather },
  { id: 'ferris-wheel', label: 'Ferris Wheel', Icon: FerrisWheel },
  { id: 'file-music', label: 'File Music', Icon: FileMusic },
  { id: 'fingerprint', label: 'Fingerprint', Icon: Fingerprint },
  { id: 'fire-extinguisher', label: 'Fire Extinguisher', Icon: FireExtinguisher },
  { id: 'flask-conical', label: 'Flask Conical', Icon: FlaskConical },
  { id: 'footprints', label: 'Footprints', Icon: Footprints },
  { id: 'fuel', label: 'Fuel', Icon: Fuel },
  { id: 'ghost', label: 'Ghost', Icon: Ghost },
  { id: 'glass-water', label: 'Glass Water', Icon: GlassWater },
  { id: 'globe', label: 'Globe', Icon: Globe },
  { id: 'goal', label: 'Goal', Icon: Goal },
  { id: 'grape', label: 'Grape', Icon: Grape },
  { id: 'guitar', label: 'Guitar', Icon: Guitar },
  { id: 'hand', label: 'Hand', Icon: Hand },
  { id: 'hard-hat', label: 'Hard Hat', Icon: HardHat },
  { id: 'heart-handshake', label: 'Heart Handshake', Icon: HeartHandshake },
  { id: 'heart-pulse', label: 'Heart Pulse', Icon: HeartPulse },
  { id: 'hotel', label: 'Hotel', Icon: Hotel },
  { id: 'ice-cream-bowl', label: 'Ice Cream Bowl', Icon: IceCreamBowl },
  { id: 'joystick', label: 'Joystick', Icon: Joystick },
  { id: 'lamp', label: 'Lamp', Icon: Lamp },
  { id: 'languages', label: 'Languages', Icon: Languages },
  { id: 'library', label: 'Library', Icon: Library },
  { id: 'life-buoy', label: 'Life Buoy', Icon: LifeBuoy },
  { id: 'lightbulb', label: 'Lightbulb', Icon: Lightbulb },
  { id: 'lollipop', label: 'Lollipop', Icon: Lollipop },
  { id: 'luggage', label: 'Luggage', Icon: Luggage },
  { id: 'magnet', label: 'Magnet', Icon: Magnet },
  { id: 'map', label: 'Map', Icon: Map },
  { id: 'martini', label: 'Martini', Icon: Martini },
  { id: 'megaphone', label: 'Megaphone', Icon: Megaphone },
  { id: 'mic-vocal', label: 'Mic Vocal', Icon: MicVocal },
  { id: 'milk', label: 'Milk', Icon: Milk },
  { id: 'monitor', label: 'Monitor', Icon: Monitor },
  { id: 'moon-star', label: 'Moon Star', Icon: MoonStar },
  { id: 'mountain-snow', label: 'Mountain Snow', Icon: MountainSnow },
  { id: 'mouse', label: 'Mouse', Icon: Mouse },
  { id: 'music2', label: 'Music 2', Icon: Music2 },
  { id: 'music3', label: 'Music 3', Icon: Music3 },
  { id: 'music4', label: 'Music 4', Icon: Music4 },
  { id: 'newspaper', label: 'Newspaper', Icon: Newspaper },
  { id: 'notebook', label: 'Notebook', Icon: Notebook },
  { id: 'nut', label: 'Nut', Icon: Nut },
  { id: 'orbit', label: 'Orbit', Icon: Orbit },
  { id: 'package', label: 'Package', Icon: Package },
  { id: 'paintbrush', label: 'Paintbrush', Icon: Paintbrush },
  { id: 'parking-meter', label: 'Parking Meter', Icon: ParkingMeter },
  { id: 'piano', label: 'Piano', Icon: Piano },
  { id: 'piggy-bank', label: 'Piggy Bank', Icon: PiggyBank },
  { id: 'pill', label: 'Pill', Icon: Pill },
  { id: 'plane-takeoff', label: 'Plane Takeoff', Icon: PlaneTakeoff },
  { id: 'plug', label: 'Plug', Icon: Plug },
  { id: 'pocket-knife', label: 'Pocket Knife', Icon: PocketKnife },
  { id: 'podcast', label: 'Podcast', Icon: Podcast },
  { id: 'printer', label: 'Printer', Icon: Printer },
  { id: 'projector', label: 'Projector', Icon: Projector },
  { id: 'puzzle', label: 'Puzzle', Icon: Puzzle },
  { id: 'qr-code', label: 'Qr Code', Icon: QrCode },
  { id: 'rainbow', label: 'Rainbow', Icon: Rainbow },
  { id: 'rat', label: 'Rat', Icon: Rat },
  { id: 'receipt', label: 'Receipt', Icon: Receipt },
  { id: 'refrigerator', label: 'Refrigerator', Icon: Refrigerator },
  { id: 'ribbon', label: 'Ribbon', Icon: Ribbon },
  { id: 'roller-coaster', label: 'Roller Coaster', Icon: RollerCoaster },
  { id: 'rose', label: 'Rose', Icon: Rose },
  { id: 'route', label: 'Route', Icon: Route },
  { id: 'ruler', label: 'Ruler', Icon: Ruler },
  { id: 'salad', label: 'Salad', Icon: Salad },
  { id: 'satellite', label: 'Satellite', Icon: Satellite },
  { id: 'scan-face', label: 'Scan Face', Icon: ScanFace },
  { id: 'shirt', label: 'Shirt', Icon: Shirt },
  { id: 'shopping-bag', label: 'Shopping Bag', Icon: ShoppingBag },
  { id: 'shopping-cart', label: 'Shopping Cart', Icon: ShoppingCart },
  { id: 'shrub', label: 'Shrub', Icon: Shrub },
  { id: 'skull', label: 'Skull', Icon: Skull },
  { id: 'snail', label: 'Snail', Icon: Snail },
  { id: 'sofa', label: 'Sofa', Icon: Sofa },
  { id: 'speaker', label: 'Speaker', Icon: Speaker },
  { id: 'sprout', label: 'Sprout', Icon: Sprout },
  { id: 'stethoscope', label: 'Stethoscope', Icon: Stethoscope },
  { id: 'sun-moon', label: 'Sun Moon', Icon: SunMoon },
  { id: 'sunrise', label: 'Sunrise', Icon: Sunrise },
  { id: 'sunset', label: 'Sunset', Icon: Sunset },
  { id: 'sword', label: 'Sword', Icon: Sword },
  { id: 'swords', label: 'Swords', Icon: Swords },
  { id: 'syringe', label: 'Syringe', Icon: Syringe },
  { id: 'tag', label: 'Tag', Icon: Tag },
  { id: 'tent-tree', label: 'Tent Tree', Icon: TentTree },
  { id: 'theater', label: 'Theater', Icon: Theater },
  { id: 'thumbs-up', label: 'Thumbs Up', Icon: ThumbsUp },
  { id: 'toy-brick', label: 'Toy Brick', Icon: ToyBrick },
  { id: 'tractor', label: 'Tractor', Icon: Tractor },
  { id: 'traffic-cone', label: 'Traffic Cone', Icon: TrafficCone },
  { id: 'tree-pine', label: 'Tree Pine', Icon: TreePine },
  { id: 'truck', label: 'Truck', Icon: Truck },
  { id: 'user', label: 'User', Icon: User },
  { id: 'venetian-mask', label: 'Venetian Mask', Icon: VenetianMask },
  { id: 'video', label: 'Video', Icon: Video },
  { id: 'volume2', label: 'Volume 2', Icon: Volume2 },
  { id: 'wand-sparkles', label: 'Wand Sparkles', Icon: WandSparkles },
  { id: 'waves', label: 'Waves', Icon: Waves },
  { id: 'wheat', label: 'Wheat', Icon: Wheat },
  { id: 'wifi', label: 'Wifi', Icon: Wifi },
  { id: 'wind', label: 'Wind', Icon: Wind },
  { id: 'worm', label: 'Worm', Icon: Worm },
  { id: 'zap', label: 'Zap', Icon: Zap },
]

export const DEFAULT_EVENT_ICON_ID: EventIconId = 'calendar-days'

export function getEventIcon(id: EventIconId): LucideIcon {
  return (
    EVENT_ICON_OPTIONS.find((option) => option.id === id)
      ?.Icon ?? CalendarDays
  )
}

type EventNameFieldProps = {
  id: string
  value: string
  onChange: (value: string) => void
  iconId: EventIconId
  onIconChange: (iconId: EventIconId) => void
  onKeyDown?: (event: KeyboardEvent<HTMLInputElement>) => void
}

export function EventNameField({
  id,
  value,
  onChange,
  iconId,
  onIconChange,
  onKeyDown,
}: EventNameFieldProps) {
  const [isPickerOpen, setIsPickerOpen] = useState(false)
  const rootRef = useRef<HTMLDivElement>(null)
  const pickerId = useId()
  const SelectedIcon = getEventIcon(iconId)

  useEffect(() => {
    if (!isPickerOpen) return

    const handlePointerDown = (event: MouseEvent | TouchEvent) => {
      const target = event.target as Node
      if (!rootRef.current?.contains(target)) {
        setIsPickerOpen(false)
      }
    }

    document.addEventListener('mousedown', handlePointerDown)
    document.addEventListener('touchstart', handlePointerDown)

    return () => {
      document.removeEventListener('mousedown', handlePointerDown)
      document.removeEventListener('touchstart', handlePointerDown)
    }
  }, [isPickerOpen])

  return (
    <div className="event-name-field" ref={rootRef}>
      <div className="event-name-field__row">
        <button
          type="button"
          className="event-name-field__icon-button"
          aria-label="イベントアイコンを選ぶ"
          aria-expanded={isPickerOpen}
          aria-controls={pickerId}
          onClick={() => setIsPickerOpen((open) => !open)}
        >
          <SelectedIcon
            className="event-name-field__icon"
            strokeWidth={1.75}
            aria-hidden="true"
          />
        </button>

        <input
          id={id}
          type="text"
          className="event-name-field__input"
          value={value}
          onChange={(event) => onChange(event.target.value)}
          onKeyDown={onKeyDown}
          placeholder="イベント名(最大10文字)"
          maxLength={10}
          inputMode="text"
          enterKeyHint="done"
        />
      </div>

      {isPickerOpen ? (
        <div
          id={pickerId}
          className="event-name-field__picker"
          role="listbox"
          aria-label={`イベントアイコン（${EVENT_ICON_OPTIONS.length}種類）`}
          onWheel={(event) => event.stopPropagation()}
          onTouchMove={(event) => event.stopPropagation()}
        >
          {EVENT_ICON_OPTIONS.map(({ id: optionId, label, Icon }) => {
            const isSelected = optionId === iconId

            return (
              <button
                key={optionId}
                type="button"
                role="option"
                aria-selected={isSelected}
                aria-label={label}
                className={`event-name-field__picker-option${
                  isSelected
                    ? ' event-name-field__picker-option--selected'
                    : ''
                }`}
                onClick={() => {
                  onIconChange(optionId)
                  setIsPickerOpen(false)
                }}
              >
                <Icon
                  className="event-name-field__picker-icon"
                  strokeWidth={1.75}
                  aria-hidden="true"
                />
              </button>
            )
          })}
        </div>
      ) : null}
    </div>
  )
}
